In [ ]:
import numpy as np
from pandas import Series,DataFrame
import pandas as pd

In [ ]:
#Now we'll learn how to deal with missing data, a very common task when analyzing datasets!

data = Series(['one','two', np.nan, 'four'])

In [ ]:
#Show data
data.rename('A')

0     one
1     two
2     NaN
3    four
Name: A, dtype: object

In [ ]:

--





#Find the missing values
data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [ ]:
#We can simply drop the NAN
data.dropna()

0     one
1     two
3    four
dtype: object

In [ ]:
# In a DataFrame we need to be a little more careful!

dframe = DataFrame([[1,2,3],[np.nan,5,6],[7,np.nan,9],[np.nan,np.nan,np.nan]])

In [ ]:
#Show
dframe

     0    1    2
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  7.0  NaN  9.0
3  NaN  NaN  NaN

In [ ]:
clean_dframe = dframe.dropna()

In [ ]:
#Show
clean_dframe

     0    1    2
0  1.0  2.0  3.0

In [ ]:
#Note all rows where an NA occured was a drop of the entire row

In [ ]:
#We can also specify to only drop rows that are complete missing all data
dframe.dropna(how='all')

     0    1    2
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  7.0  NaN  9.0

In [ ]:
#Or we can specify to drop columns with missing data
dframe.dropna(axis=1)

#This should drop all columns out since every column contains at least 1 NAN

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [ ]:
#We can also threshold teh missing data as well

#For example if we only want rows with at least 3 data points
dframe2 = DataFrame([[1,2,3,np.nan],[2,np.nan,5,6],[np.nan,7,np.nan,9],[1,np.nan,np.nan,np.nan]])

#Show
dframe2

     0    1    2    3
0  1.0  2.0  3.0  NaN
1  2.0  NaN  5.0  6.0
2  NaN  7.0  NaN  9.0
3  1.0  NaN  NaN  NaN

In [ ]:
#Droppin any rows tht dont have at least 2 data points
dframe2.dropna(thresh=2)

     0    1    2    3
0  1.0  2.0  3.0  NaN
1  2.0  NaN  5.0  6.0
2  NaN  7.0  NaN  9.0

In [ ]:
#Dropiing rows without at least 3 data points
dframe2.dropna(thresh=3)

     0    1    2    3
0  1.0  2.0  3.0  NaN
1  2.0  NaN  5.0  6.0

In [ ]:
#We can also fill any NAN
dframe2.fillna(1)

     0    1    2    3
0  1.0  2.0  3.0  1.0
1  2.0  1.0  5.0  6.0
2  1.0  7.0  1.0  9.0
3  1.0  1.0  1.0  1.0

In [ ]:
#Can also fill in diff values for diff columns
dframe2.fillna({0:0,1:1,2:2,3:3})

     0    1    2    3
0  1.0  2.0  3.0  3.0
1  2.0  1.0  5.0  6.0
2  0.0  7.0  2.0  9.0
3  1.0  1.0  2.0  3.0

In [ ]:
#Note that we still have access to the original dframe
dframe2

     0    1    2    3
0  1.0  2.0  3.0  NaN
1  2.0  NaN  5.0  6.0
2  NaN  7.0  NaN  9.0
3  1.0  NaN  NaN  NaN

In [ ]:
#If we want to modify the exsisting object, use inplace
dframe2.fillna(0,inplace=True)

In [ ]:
#Now let's see the dframe
dframe2

     0    1    2    3
0  1.0  2.0  3.0  0.0
1  2.0  0.0  5.0  6.0
2  0.0  7.0  0.0  9.0
3  1.0  0.0  0.0  0.0

In [ ]:
#Awesome! Next we'll learn about Index Hierarchy