In [ ]:
import pandas as pd
sales = pd.Series([120,150,180,210])
sales

0    120
1    150
2    180
3    210
dtype: int64

In [ ]:
marks = pd.Series([172,81,69,901])
marks

0    172
1     81
2     69
3    901
dtype: int64

In [ ]:
marks = pd.Series([172,81,69,901])
marks.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
temperature = pd.Series([28,31,30,29],index = ['mon','tue','wed','thur'])
temperature

mon     28
tue     31
wed     30
thur    29
dtype: int64

In [ ]:
population = pd.Series([35, 42, 31], index=['Delhi','Mumbai','Jaipur'])
population['Jaipur']

np.int64(31)

In [ ]:
score = pd.Series([35, 68, 44, 79, 52])
score[score>60]

1    68
3    79
dtype: int64

In [ ]:
subjects = pd.Series([76, 83, 91], index=['Physics', 'Chemistry', ' Math'])
'Chemistry' in subjects.index

True

In [ ]:
subjects.to_dict()

{'Physics': 76, 'Chemistry': 83, ' Math': 91}

In [ ]:
prices = {'Pen': 10, 'Notebook': 55, 'Bag': 700}
price_series = pd.Series(prices)
price_series

Pen          10
Notebook     55
Bag         700
dtype: int64

In [ ]:
s=pd.isnull(price_series)
s

Pen         False
Notebook    False
Bag         False
dtype: bool

In [ ]:
sales.name = 'Monthly Sales'
sales.index.name = 'Month'
sales

Month
0    120
1    150
2    180
3    210
Name: Monthly Sales, dtype: int64

In [ ]:
sales.index.name = 'Month'
sales

Month
0    120
1    150
2    180
3    210
Name: Monthly Sales, dtype: int64

In [ ]:
prices = {'Pen' : 10, 'Notebook' : 55, 'Bag' : 700}
price_series = pd.Series(prices)
price_series

Pen          10
Notebook     55
Bag         700
dtype: int64

In [ ]:
data = {'A':20,'B':30,'C':40}
s=pd.Series(data, index=['A','B','C','D'])
s.notnull()

A     True
B     True
C     True
D    False
dtype: bool

In [ ]:
import pandas as pd
data = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(data[data % 20 == 0])

b    20
d    40
dtype: int64

In [ ]:
import pandas as pd
s = pd.Series([500, 600, 700], index=['East', 'West', 'North'])
print("'West' in s:")
print('West' in s)
print("\n500 in s:")
print(500 in s)
print("\n500 in s.values:")
print(500 in s.values)

'West' in s:
True

500 in s:
False

500 in s.values:
True

In [ ]:
import pandas as pd
city_data = {"Delhi": 80, "Pune": 65, "Kochi": 70}
ordered_index = ["Delhi", "Kochi", "Pune", "Chennai"]
city_series = pd.Series(city_data, index=ordered_index)

print(city_series)

Delhi      80.0
Kochi      70.0
Pune       65.0
Chennai     NaN
dtype: float64

In [ ]:
import pandas as pd
info = pd.Series([1, 2, None, 4], index=['a', 'b', 'c', 'd'])
print(info.notnull()['c'])

False

In [ ]:
import pandas as pd

s = pd.Series({'W': 5, 'X': 10, 'Y': 15}, index=['W', 'X', 'Y', 'Z'])
print(s)
pd.isnull(s)
pd.notnull(s)
s_filled = s.fillna(0)
s_dropped = s.dropna()

W     5.0
X    10.0
Y    15.0
Z     NaN
dtype: float64

In [ ]:
import pandas as pd
s1 = pd.Series([10, 20, 30], index=['A', 'B', 'C'])
s2 = pd.Series([1, 2, 3], index=['C', 'A', 'B'])
result = s1 + s2
print(result)

A    12
B    23
C    31
dtype: int64

In [ ]:
import pandas as pd

s1 = pd.Series({'A': 12, 'B': 18})
s2 = pd.Series({'B': 5, 'C': 9})
result = s1.add(s2, fill_value=0)
print(result)

A    12.0
B    23.0
C     9.0
dtype: float64

In [ ]:
import pandas as pd
stock = pd.Series([25, 40, 18], index=['Item1', 'Item2', 'Item3'])
stock_dict = stock.to_dict()
stock2 = pd.Series(stock_dict)
print("Dictionary:")
print(stock_dict)

print("\nReconstructed Series (stock2):")
print(stock2)

Dictionary:
{'Item1': 25, 'Item2': 40, 'Item3': 18}

Reconstructed Series (stock2):
Item1    25
Item2    40
Item3    18
dtype: int64

In [ ]:
import pandas as pd
marks = {'Maths': 88, 'Science': 74, 'English': 69, 'History': 81}
marks_series = pd.Series(marks, index=['History', 'English', 'Science', 'Maths'])
result = marks_series[marks_series > 70]
print("Filtered Series:")
print(result)

Filtered Series:
History    81
Science    74
Maths      88
dtype: int64

In [ ]:
series = name
ms.series.name ='Branch'